name: RustDesk Static ID Runner

on:
  workflow_dispatch:

jobs:
  rustdesk:
    runs-on: windows-latest
    steps:
      - name: Setup RustDesk Config Files
        run: |
          $configPath = "$env:APPDATA\RustDesk\config"
          New-Item -ItemType Directory -Force -Path $configPath | Out-Null

          # Static ID and password
          "mygithubvm" | Out-File "$configPath\id" -Encoding ascii
          "123456" | Out-File "$configPath\passwd" -Encoding ascii

          # Optional: Configure your own RustDesk relay/rendezvous server here
          @"
relay=your.vps.ip:21117
api_server=
key=
"@ | Out-File "$configPath\RustDesk2.toml" -Encoding ascii

      - name: Download RustDesk
        run: |
          Invoke-WebRequest -Uri "https://github.com/rustdesk/rustdesk/releases/download/1.4.0/rustdesk-1.4.0-x86_64.exe" -OutFile "rustdesk.exe"

      - name: Launch RustDesk (Headless)
        run: |
          Start-Process -FilePath ".\rustdesk.exe" -WindowStyle Hidden
          Start-Sleep -Seconds 30

      - name: Confirm Config Files
        run: |
          Get-Content "$env:APPDATA\RustDesk\config\id"
          Get-Content "$env:APPDATA\RustDesk\config\passwd"
